sudo: required

lang: bash

services:
  - docker

before_install:
  - docker build -t pragkent/oauth2-proxy:2.2.0 .

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push pragkent/oauth2-proxy:2.2.0
